---
title: "Project 4"
execute:
  echo: false
description: OkCupid Data Ethics
author: Rowan Norenberg
date: November 12, 2025
format: html
---

In 2015, “OkCupid Data for Introductory Statistics and Data Science Courses” by Albert Y. Kim and Adriana Escobedo-Land was published to the academic journal Taylor & Francis online. The dataset was published with the intention of being used for teaching data science and statistics. However, by 2016, the dataset was already appearing in magazines like Fortune, with those who had encountered the dataset claiming the dataset was found to have identifiable information – that is, someone reading the dataset could identify the real person that the OkCupid profile data was scraped from. The dating profile contained extremely sensitive information, ranging from job, salary, age, and height to religion, sexual orientation, and drug use. Being able to identify someone easily from a large, easy to access dataset led to calls for review of the dataset.

Consent

None of the participants consented to be part of the dataset. In the OkCupid privacy policy, users agree to their information being visible to other members on the service, and their data being shared with service providers and operating partner companies. The privacy policy repeatedly insists that privacy and consent are important to the company. It is not unreasonable for a user to read this policy and assume that their personal data would not be scraped for a public database. However, the creators of the dataset were given permission not by the individual participants but rather by the president and founders of the company. The data scraping was thus not illegal. However, Tiffany Xiao &Yifan Ma (2021) points out that legislation about technology and data are outdated, and that while privacy violations are not often illegal, they are still immoral.

Anonymity

The data was found to have identifiable information. The data is from the 2010s, so the data is certainly not old enough to be anonymous. The data contained physical descriptions including height, body type, and race, as well as age, religion, occupation, sex, education, pets, children, and star sign. They also included 10 essay questions which were answered by participants. That combined with the knowledge that all of these people lived within 25 miles of San Francisco – at an exact date which was later removed – and you can definitely identify participants. The data was not at all anonymized until reviews were requested, when essay questions were randomized by row, the exact date was replaced with “from the 2010s”, and random noise was added to the age variable.

Participants

Generalizing people by sexual orientation is not an algorithm that should be created. That sort of data can be used for little good and substantial harm. To my knowledge the dataset is not currently being used for unintended purposes, but this is not a good precedent to set. Mass amounts of personal information can be easily used for systemic discrimination.

Availability

This data was made publicly available on GitHub, as well as accessible through Taylor & Francis. You can see and access the data freely online.

Kim, A. Y., & Escobedo-Land, A. (2015). OkCupid Data for Introductory Statistics and Data Science Courses. *Journal of Statistics Education*, *23*(2). <https://doi.org/10.1080/10691898.2015.11889737>

*Privacy Policy*. (n.d.). OkCupid. Retrieved December 10, 2025, from <https://okcupid-app.zendesk.com/hc/en-us/articles/22780694078491-Privacy-Policy>

Xiao, T., & Ma, Y. (2021). A Letter to the Journal of Statistics and Data Science Education—A Call for Review of “OkCupid Data for Introductory Statistics and Data Science Courses” by Albert Y. Kim and Adriana Escobedo-Land. *Journal of Statistics and Data Science Education*, *29*(2), 214–215. <https://doi.org/10.1080/26939169.2021.1930812>
