
---
title: "Tidy Tuesday - D&D Monsters"
execute:
  echo: false
description: |
  Analysis of D&D data from TidyTuesday
author: Rowan Norenberg
date: September 24, 2025
format: html
---

This is a plot I made comparing the different types of D&D monsters with their total hit points and their strength score / modifier. 

```{r, warning = FALSE, message = FALSE}

#| echo: false
library(tidyverse)
library(ggplot2)

monsters <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-05-27/monsters.csv', show_col_types = FALSE)
```

```{r}
ggplot(monsters, aes(x = hp_number, y = str, color = type)) +
  geom_point() +
  labs(
    x = "Hit Points",
    y = "Strength Modifier",
    title = "D&D Monsters by Type",
  )
```


Tidyverse Link: https://github.com/rfordatascience/tidytuesday/tree/main/data/2024/2024-12-17

Dataset Citation: 
Harmon J (2025). dddata: Data from the Dungeons and Dragons System Reference Document. R package version 0.0.0.9000, https://github.com/jonthegeek/dddata.  

